/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PuntoPlast;

import claseconexion.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Iva extends javax.swing.JFrame {

    /**
     * Creates new form Iva
     */
    public Iva() {
        this.setLocationRelativeTo(null);
        initComponents();
        cargar();
    }

    void cargar() {
        //carga todos los productos o los selecionados
        try{
            String cons="SELECT Porc_iva, Fecha_iva FROM IVA WHERE Fecha_iva=(SELECT MAX(Fecha_iva) FROM IVA)";//Selecciona el ultimo IVA seleccionado
            
            Statement st= cn.createStatement();
            ResultSet rs = st.executeQuery(cons);
            
            while(rs.next()){ 
                int iva= Integer.parseInt(rs.getString("Porc_iva"));
                actual.setText("Actual: "+iva+"%");
                txtiva.setText(Integer.toString(iva));
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error: No se pudo encontrar iva.");
                System.out.println(e.getMessage());
            }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        actual = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opciones - Iva");
        setMinimumSize(new java.awt.Dimension(250, 120));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese el porcentaje de Iva a aplicar");

        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        actual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actual.setText("Actual: xx");

        txtiva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtivaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnaceptar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(actual, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnaceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtiva)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actual))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        if(txtiva.getText().trim().length()>0){//Si tiene numeros
            int value = Integer.parseInt(txtiva.getText());            
            
            try {//Busca si existe el iva tipeado
                String Porc_iva="";
                String select="SELECT Porc_iva FROM iva WHERE Porc_iva="+value+"";
                
                Statement st1= cn.createStatement();
                ResultSet rs1=st1.executeQuery(select);
                
                while(rs1.next()){
                    Porc_iva=rs1.getString("Porc_iva");                
                }
                
                if(Porc_iva.equals("")){//Si no existe el iva tipeado, lo añade a la BD
                    try {
                        String insert="INSERT INTO iva(Porc_iva, Fecha_iva) VALUES(?, CURRENT_TIMESTAMP)";
                        
                        PreparedStatement pst= cn.prepareStatement(insert);
                        pst.setInt(1, value);
                        int n=pst.executeUpdate();
                        
                        if(n>0){
                            JOptionPane.showMessageDialog(this, "Registro Guardado con Exito");
                            cargar();
                        }                        
                        
                    }catch(Exception e){                    
                        JOptionPane.showMessageDialog(this, "Error al guardar, operacion cancelada");
                        System.out.print(e.getMessage());                    
                    }
                }else{//Si existe, actualiza fecha
                    try {
                        String update="UPDATE iva SET Fecha_iva=CURRENT_TIMESTAMP WHERE Porc_iva="+value+"";
                        
                        PreparedStatement pst= cn.prepareStatement(update);
                        int n=pst.executeUpdate();
                        
                        if(n>0){
                            JOptionPane.showMessageDialog(this, "Registro Guardado con Exito");
                            cargar();
                        }                        
                    }catch(Exception e){                    
                        JOptionPane.showMessageDialog(this, "Error al guardar, operacion cancelada");
                        System.out.print(e.getMessage());
                    }     
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al guardar, operacion cancelada");
                System.out.print(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese un valor para el iva");
        }
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void txtivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtivaKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
        if(txtiva.getText().length()>=2) evt.consume();        
    }//GEN-LAST:event_txtivaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actual;
    private javax.swing.JButton btnaceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtiva;
    // End of variables declaration//GEN-END:variables
    Conectar cc = new Conectar();
    Connection cn = cc.conexion();
}
