/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PuntoPlast;

import claseconexion.Conectar;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Cedenos
 */
public class ReporteFacturas extends javax.swing.JFrame {
    /**
     * Creates new form reporteFacturas
     */
    public ReporteFacturas() {
        initComponents();
        Limpiar();
    }
    
    void Bloquear(){
        txtcedula.setEnabled(false);        
        calendario1.setEnabled(false);
        calendario1.setDate(null);
        calendario2.setEnabled(false);
        calendario2.setDate(null);        
    }
    
    public void Limpiar(){
        txtcedula.setText("");
        calendario1.setDate(null);
        calendario2.setDate(null);
        Bloquear();
        PlaceHolder();
    }
    
    public void PlaceHolder(){
        ph.Mensaje(txtcedula, "Introduzca una cedula...", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_pestaña = new javax.swing.JTabbedPane();
        panel_fac = new javax.swing.JPanel();
        rdtodo = new javax.swing.JRadioButton();
        rdfecha = new javax.swing.JRadioButton();
        rdcliente = new javax.swing.JRadioButton();
        calendario2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        calendario1 = new com.toedter.calendar.JDateChooser();
        btnimprimir = new javax.swing.JButton();
        txtcedula = new javax.swing.JTextField();
        panel_estad = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reporte de facturas");

        panel_pestaña.setFocusable(false);

        buttonGroup1.add(rdtodo);
        rdtodo.setText("Todas las facturas.");
        rdtodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdtodoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdfecha);
        rdfecha.setText("Por fecha:");
        rdfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdfechaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdcliente);
        rdcliente.setText("Por cliente:");
        rdcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdclienteActionPerformed(evt);
            }
        });

        calendario2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calendario2FocusGained(evt);
            }
        });

        jLabel1.setText("-");

        calendario1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                calendario1FocusGained(evt);
            }
        });

        btnimprimir.setText("Imprimir");
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });

        txtcedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcedulaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtcedulaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panel_facLayout = new javax.swing.GroupLayout(panel_fac);
        panel_fac.setLayout(panel_facLayout);
        panel_facLayout.setHorizontalGroup(
            panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_facLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_facLayout.createSequentialGroup()
                        .addComponent(calendario1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(rdfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rdcliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdtodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calendario2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtcedula))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_facLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnimprimir)
                .addGap(24, 24, 24))
        );
        panel_facLayout.setVerticalGroup(
            panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_facLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rdtodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdcliente)
                    .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_facLayout.createSequentialGroup()
                        .addComponent(rdfecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(calendario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_facLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(calendario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnimprimir)
                .addGap(21, 21, 21))
        );

        panel_pestaña.addTab("Facturas", panel_fac);

        javax.swing.GroupLayout panel_estadLayout = new javax.swing.GroupLayout(panel_estad);
        panel_estad.setLayout(panel_estadLayout);
        panel_estadLayout.setHorizontalGroup(
            panel_estadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );
        panel_estadLayout.setVerticalGroup(
            panel_estadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        panel_pestaña.addTab("Estadisticas", panel_estad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_pestaña)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_pestaña)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        if(rdtodo.isSelected()){
            JasperReport jru = null;                
                try {
                    jru = (JasperReport) JRLoader.loadObject(getClass().getResource("reporteListadoFacturas.jasper"));
                    JasperPrint jpu = JasperFillManager.fillReport(jru, null, cc.conexion());
                    
                    JasperViewer jvu = new JasperViewer(jpu, false);
                    
                    jvu.setVisible(true);
                    jvu.setTitle("Reporte de Facturas");
                    jvu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                } catch (JRException ex) {
                    Logger.getLogger(ConsultasClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
            if(rdcliente.isSelected()){
                String ced=txtcedula.getText();
                JasperReport jru = null;                
                
                try {
                    jru = (JasperReport) JRLoader.loadObject(getClass().getResource("reporteFacturaCliente.jasper"));
                    
                    //Parametro para generar una consulta especifica
                    Map parametros = new HashMap();
                    parametros.clear();
                    parametros.put("Cedula", ced);//Nombre del parametro del reporte y la variable que guardara
                                    
                    JasperPrint jpu = JasperFillManager.fillReport(jru, parametros, cc.conexion());
                    
                    JasperViewer jvu = new JasperViewer(jpu, false);
                    jvu.setVisible(true);
                    jvu.setTitle("Reporte de Facturas por Cliente");
                    jvu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                } catch (JRException ex) {
                    Logger.getLogger(ConsultasClientes.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                if(rdfecha.isSelected()){
                    Date fecha1=calendario1.getDate();
                    Date fecha2=calendario2.getDate();
                    SimpleDateFormat formatofecha= new SimpleDateFormat("yyyy-MM-dd");
                    String Fecha1=""+formatofecha.format(fecha1);
                    String Fecha2=""+formatofecha.format(fecha2);
                    
                    JasperReport jru = null;                
                
                    try {
                        jru = (JasperReport) JRLoader.loadObject(getClass().getResource("reporteFacturaFecha.jasper"));
                    
                        //Parametro para generar una consulta especifica
                        Map parametros = new HashMap();  
                        parametros.clear();
                        parametros.put("Fecha1", Fecha1);//Nombre del parametro del reporte y la variable que guardara
                        parametros.put("Fecha2", Fecha2);//Nombre del parametro del reporte y la variable que guardara
                                    
                        JasperPrint jpu = JasperFillManager.fillReport(jru, parametros, cc.conexion());
                    
                        JasperViewer jvu = new JasperViewer(jpu, false);
                        jvu.setVisible(true);
                        jvu.setTitle("Reporte de Facturas por Cliente");
                        jvu.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    } catch (JRException ex) {
                        Logger.getLogger(ConsultasClientes.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                }else{
                    JOptionPane.showMessageDialog(null, "Por favor, seleccione una opción.");
                }
            }
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void rdtodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdtodoActionPerformed
        // TODO add your handling code here:
        Limpiar();       
    }//GEN-LAST:event_rdtodoActionPerformed

    private void rdclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdclienteActionPerformed
        // TODO add your handling code here:
        Limpiar();
        txtcedula.setEnabled(true);
    }//GEN-LAST:event_rdclienteActionPerformed

    private void rdfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdfechaActionPerformed
        // TODO add your handling code here:
        Limpiar();
        calendario1.setEnabled(true);
        calendario2.setEnabled(true);
    }//GEN-LAST:event_rdfechaActionPerformed

    private void txtcedulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusGained
        // TODO add your handling code here:
        ph.Comparar(txtcedula);
    }//GEN-LAST:event_txtcedulaFocusGained

    private void txtcedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcedulaFocusLost
        // TODO add your handling code here:
        if(txtcedula.getText().trim().length()==0){
            PlaceHolder();
        }
    }//GEN-LAST:event_txtcedulaFocusLost

    private void calendario1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calendario1FocusGained
        // TODO add your handling code here:
        //Todavia no funciona
        
        System.out.println("Focus calendario1");
        if(calendario2.getDate()!=null){
            calendario1.setMaxSelectableDate(calendario2.getDate());
        }
    }//GEN-LAST:event_calendario1FocusGained

    private void calendario2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_calendario2FocusGained
        // TODO add your handling code here:
        //Todavia no funciona
        
        System.out.println("Focus calendario2");
        if(calendario1.getDate()!=null){
            calendario2.setMinSelectableDate(calendario1.getDate());
        }
    }//GEN-LAST:event_calendario2FocusGained

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnimprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser calendario1;
    private com.toedter.calendar.JDateChooser calendario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_estad;
    private javax.swing.JPanel panel_fac;
    private javax.swing.JTabbedPane panel_pestaña;
    private javax.swing.JRadioButton rdcliente;
    private javax.swing.JRadioButton rdfecha;
    private javax.swing.JRadioButton rdtodo;
    private javax.swing.JTextField txtcedula;
    // End of variables declaration//GEN-END:variables
    Conectar cc= new Conectar();
    Connection cn = cc.conexion();
    PlaceHolder ph=new PlaceHolder();
}
